### ISSUE TITLE
生成した画像をpublicに置くのが正しいのか問題

### ISSUE THREAD

**Issue by mizucoffee** [jphacks/D_2011#29]

**Comment by mizucoffee** [comment]
画像返せば良い...?

**Comment by penguin4731** [comment]
データベースにbase64のコード列だけ残すのでどうでしょうか？
サーバー負荷減らすためにも、アプリからの要求で毎回つくるのもなーと思ってたので！

**Comment by mizucoffee** [comment]
base64のが大きいんだよねー（4/3倍になる）
そしてDBに大きい文字列は置きたくない><

**Comment by mizucoffee** [comment]
個人的には毎回生成させてもいいと思ってる...負荷は測ってみたいけど

**Comment by penguin4731** [comment]
画像を保持する必要があるのが、Zoomのカメラだけなのでそこの処理を画像を保存することなくできれば、
生成した瞬間に削除でなんとかはなるはずです。
どっちにしてもどこかへの保存は必須なので、仕方ない気が...

**Comment by mizucoffee** [comment]
実は生成した画像ものをそのままパイプでffmpegに渡せる

**Comment by penguin4731** [comment]
@mizucoffee 今使ってる画像生成のクセ（というかバグ）でパス関連をrubyで書くとうまく取得しないので、blobで渡すの割と早急にやったほうがいいかもです

**Comment by mizucoffee** [comment]
事件や...笑
今やってるタスク終わったらやりまーす

**Comment by mizucoffee** [comment]
出来た！！！！！！
