### ISSUE TITLE
API設計見直し

### ISSUE THREAD

**Issue by mizucoffee** [jphacks/D_2011#40]
`/api/meeting/:meeting_id/<action>`
形式に統一しても良さそう

**Comment by penguin4731** [comment]
@mizucoffee 
その方が良い気がしますー！

**Comment by penguin4731** [comment]
ミーティング作成
`POST　/api​/meeting`

ミーティング開始
`POST　/api​/meeting​/:meeting_id/start`

ミーティング終了（Aika退出）
`POST　/api​/meeting​/:meeting_id/finish`

全員ミュート&アンミュート通知
`POST　/api​/meeting​/:meeting_id/mute_all`

議題変更
`POST　/api​/meeting​/:meeting_id/agenda​_next`

アジェンダ画像
`GET　/api/meeting/:meeting_id/agenda_img`
