### ISSUE TITLE
タイマー適用する

### ISSUE THREAD

**Issue by mizucoffee** [jphacks/D_2011#8]

**Comment by Tomoya113** [comment]
@mizucoffee 
土曜日言ってた、どこから呼び出しても結果が一緒になるようにするってどういうこと？
「指定した時間に画像の変更などのミーティング周りの処理をするクラス」というよりも「指定した時間に任意のメソッドを実行するためのクラス」を作って欲しいって感じ？

**Comment by mizucoffee** [comment]
@Tomoya113 
後者を意図してた！
依存を極限まで減らしておいてほしい！こうする事によって保守効率と汎用性が上がるので！

例:
保守効率→画像生成の関数の仕様が変わった時にタイマーまでいじる必要がなくなる
汎用性→ミーティング以外でタイマーを使う必要が出たときにタイマーの修正が不要になる

**Comment by Tomoya113** [comment]
@mizucoffee 
ごもっとも。抽象化大事ですねぇ〜
